Feature/auth
NHN-BookPub/bookpub-auth pull request #2
Opened 2023-01-15 08:19 UTC by limtaewon

2023-01-15 11:18 UTC, unhas01 requested changes
prod url 수정 부탁!!

2023-01-15 11:18 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpubauth/member/filter/CustomAuthenticationFilter.java
> +    private static final String TOKEN_TYPE = "Bearer ";
"Bearer " 에서 빈칸도 의미가 있는 건가요?

2023-01-15 11:18 UTC, unhas01 commented on src/main/resources/application-prod.properties
> +book-pub.gateway=http://133.186.215.87:7070
플로팅 아이피를 쓰면 안될거 같아요

2023-01-15 11:19 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/member/filter/CustomAuthenticationFilter.java
> +    private static final String TOKEN_TYPE = "Bearer ";
넵 Bearer이 타입이고 한칸뛰고 토큰이 들어옵니다

2023-01-15 11:20 UTC, limtaewon commented on src/main/resources/application-prod.properties
> +book-pub.gateway=http://133.186.215.87:7070
수정했습니다

2023-01-15 11:21 UTC, unhas01 approved these changes

2023-01-15 11:21 UTC, seohyeon07 approved these changes
수고하셨습니다

2023-01-15 11:21 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpubauth/member/exception/NotMemberBookpubSite.java
> + * Some description here
javadoc작성부탁드려요

2023-01-15 11:21 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpubauth/token/controller/TokenController.java
> +        return null;
구현을 아직 안하신건가요? 아니면 원래 return null 이 맞을까요..?

2023-01-15 11:21 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpubauth/token/service/TokenServiceImpl.java
> +    }
return null?

2023-01-15 11:23 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/token/controller/TokenController.java
> +        return null;
구현을 아직 안했습니다 
갱신부분을 제외한 로그인기능 완료해서 1차 커밋 푸쉬 했습니당

2023-01-15 11:24 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/member/exception/NotMemberBookpubSite.java
> + * Some description here
넵! 수정했습니다

2023-01-17 01:28 UTC, nhn-academy-marco reviewed
수고하셨습니다.

2023-01-17 01:28 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubauth/config/RedisConfig.java
> +@EnableRedisHttpSession
@EnableRedisHttpSession을 사용한 이유가 있을까요?

2023-01-17 01:28 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubauth/config/RedisConfig.java
> +    public CookieSerializer cookieSerializer() {
인증서버에서 쿠키쪽 설정을 한 이유가 있을까요?

2023-01-17 01:28 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubauth/config/SecurityConfig.java
> +        http.addFilterBefore(customAuthenticationFilter(null), UsernamePasswordAuthenticationFilter.class);
UsernamePasswordAuthenticationFilter 전에 동작하기보다는  replace 해보면 어떨까요?

2023-01-17 01:28 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubauth/member/CustomUserDetails.java
> +public class CustomUserDetails implements UserDetails {
equas 와 hashcode 구현에 대해서도 . 고려해주세요.

2023-01-17 01:28 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubauth/member/dto/LoginMemberRequestDto.java
> +    private String sessionId;
sessionId를 전달받는 특별한 이유가 있을까요?
http session id 일텐데... web에만 종속?

2023-01-17 04:54 UTC, HoFe-U reviewed
수고하셨습니다.

2023-01-17 04:54 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubauth/token/util/JwtUtil.java
> +     * 생성자 이전에 실행되는 초기화 메소드
access token 과 
refresh token 의 valid time 을 위와같이 할당한 이유가있을까요?

2023-01-17 04:54 UTC, HoFe-U commented on src/main/resources/application.properties
KeyManager 가 들어가서 위의 값들을 노출하지않아야할것같습니다.

2023-01-17 05:01 UTC, limtaewon commented on src/main/resources/application.properties
빠른시일내 추가해두겠습니다

2023-01-17 05:16 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/config/SecurityConfig.java
> +        http.addFilterBefore(customAuthenticationFilter(null), UsernamePasswordAuthenticationFilter.class);
공부해보니 replace가 좋을 것 같아 수정했습니다!

2023-01-17 05:16 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/config/RedisConfig.java
> +    public CookieSerializer cookieSerializer() {
필요 없을거 같네요 수정했습니다!

2023-01-17 05:16 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/config/RedisConfig.java
> +@EnableRedisHttpSession
프론트서버와 착각해서 달아두고 따로 처리를 안했네요
수정했습니다!

2023-01-17 05:40 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/member/dto/LoginMemberRequestDto.java
> +    private String sessionId;
초반 token과 reids 이해부족으로 넣었는데 수정했습니다!

2023-01-17 05:40 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubauth/token/util/JwtUtil.java
> +     * 생성자 이전에 실행되는 초기화 메소드
구글 클라우드에서 추천해 준 시간으로 했습니다

2023-01-17 05:41 UTC, merged